# Generated by Django 6.0.5 on 2026-05-14 04:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('swarm_node_id', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('tipo', models.CharField(choices=[('vps', 'VPS'), ('dedicado', 'Dedicado'), ('cloud_vm', 'Cloud VM')], default='dedicado', max_length=20)),
                ('regiao', models.CharField(choices=[('anapolis', 'Anápolis'), ('brasilia', 'Brasília')], default='anapolis', max_length=20)),
                ('cpu_total', models.PositiveIntegerField()),
                ('ram_gb_total', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Host de Infraestrutura',
                'verbose_name_plural': 'Hosts de Infraestrutura',
                'ordering': ['regiao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_usuarios', models.PositiveIntegerField(default=0, help_text='0 = ilimitado')),
                ('max_empresas', models.PositiveIntegerField(default=1)),
                ('recursos_cpu', models.PositiveIntegerField(default=1)),
                ('recursos_ram_gb', models.PositiveIntegerField(default=2)),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('modulos_inclusos', models.ManyToManyField(blank=True, to='registry.modulo')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('email_contato', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('versao_erp', models.CharField(blank=True, max_length=20)),
                ('stack_path', models.CharField(blank=True, max_length=500)),
                ('subdominio', models.CharField(max_length=100, unique=True)),
                ('dominio_custom', models.CharField(blank=True, max_length=200)),
                ('asaas_customer_id', models.CharField(blank=True, max_length=100)),
                ('asaas_subscription_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('aguardando_provisao', 'Aguardando Provisionamento'), ('provisionando', 'Provisionando'), ('ativo', 'Ativo'), ('trial', 'Trial'), ('trial_expirado', 'Trial Expirado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado'), ('erro_provisao', 'Erro no Provisionamento'), ('atualizando', 'Atualizando')], db_index=True, default='aguardando_provisao', max_length=30)),
                ('trial_ate', models.DateField(blank=True, null=True)),
                ('data_ativacao', models.DateField(blank=True, null=True)),
                ('data_suspensao', models.DateField(blank=True, null=True)),
                ('data_cancelamento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.hostinfraestrutura')),
                ('modulos_ativos', models.ManyToManyField(blank=True, to='registry.modulo')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.plano')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionamentoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='registry.tenant')),
            ],
            options={
                'verbose_name': 'Log de Provisionamento',
                'verbose_name_plural': 'Logs de Provisionamento',
                'ordering': ['iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificado_em', models.DateTimeField(auto_now_add=True)),
                ('status_http', models.PositiveIntegerField(default=0)),
                ('latencia_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthchecks', to='registry.tenant')),
            ],
            options={
                'verbose_name': 'Health Check',
                'verbose_name_plural': 'Health Checks',
                'ordering': ['-verificado_em'],
                'get_latest_by': 'verificado_em',
            },
        ),
        migrations.CreateModel(
            name='AtualizacaoVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_anterior', models.CharField(max_length=20)),
                ('versao_nova', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('executando', 'Executando'), ('concluida', 'Concluída'), ('revertida', 'Revertida'), ('erro', 'Erro')], default='agendada', max_length=20)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('mensagem', models.TextField(blank=True)),
                ('iniciada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='registry.tenant')),
            ],
            options={
                'verbose_name': 'Atualização de Versão',
                'verbose_name_plural': 'Atualizações de Versão',
                'ordering': ['-iniciada_em'],
            },
        ),
    ]
