# Generated by Django 6.0.5 on 2026-05-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_renomear_tenant_healthcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='isento_cobranca',
            field=models.BooleanField(default=False, help_text='Marque para clientes de teste ou parceiros — nenhuma cobrança será gerada.', verbose_name='Isento de cobrança'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='motivo_isencao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo da isenção'),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='registry_cliente',
        ),
    ]
