# Generated by Django 6.0.5 on 2026-05-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_configuracaoemail_verificar_ssl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tema_site',
            field=models.CharField(choices=[('padrao', 'Padrão (e-commerce)'), ('dedetizadora', 'Dedetizadora')], default='padrao', help_text='Template visual da landing page pública do cliente.', max_length=50, verbose_name='Tema do site'),
        ),
        migrations.AlterField(
            model_name='configuracaoemail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
