# Generated by Django 6.0.5 on 2026-05-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_tema_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCloudflare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_api_token', models.CharField(help_text='Token com permissões Zone:Read + DNS:Edit em All Zones.', max_length=500, verbose_name='API Token')),
                ('server_ip', models.GenericIPAddressField(help_text='IP público do Swarm manager — usado no registro A dos domínios custom.', verbose_name='IP do Servidor')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Cloudflare',
                'verbose_name_plural': 'Configuração Cloudflare',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tema_site',
            field=models.CharField(choices=[('padrao', 'Padrão (e-commerce)'), ('dedetizadora', 'Dedetizadora (verde)'), ('dedetizadora2', 'Dedetizadora 2 (azul + animações)'), ('loja', 'Loja (claro premium)')], default='padrao', help_text='Template visual da landing page pública do cliente.', max_length=50, verbose_name='Tema do site'),
        ),
    ]
