# Generated by Django 6.0.5 on 2026-08-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_backupcliente_progresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupcliente',
            name='origem',
            field=models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Importado manualmente')], default='automatico', max_length=20),
        ),
    ]
