# Generated by Django 6.0.5 on 2026-08-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_backupcliente_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaocloudflare',
            name='cf_api_token',
            field=models.CharField(help_text='Token com permissões Zone:Read + DNS:Edit + Account:Cloudflare Tunnel:Edit em All Accounts.', max_length=500, verbose_name='API Token'),
        ),
    ]
