# Generated by Django 6.0.5 on 2026-08-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_alter_configuracaocloudflare_cf_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupcliente',
            name='mensagem_restauracao',
            field=models.TextField(blank=True),
        ),
    ]
