# Generated by Django 6.0.5 on 2026-09-05 00:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_backupcliente_mensagem_restauracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersaoAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=20, unique=True)),
                ('erp_minimo', models.CharField(blank=True, help_text='Comparação semver X.Y.Z (mesmo formato de Cliente.versao_erp). Em branco = sem requisito de versão do ERP.', max_length=20, verbose_name='Versão mínima do ERP exigida')),
                ('download_url', models.URLField(max_length=500)),
                ('sha256', models.CharField(help_text='Hash SHA256 do ZIP em hexadecimal (64 caracteres) — abra o arquivo .sha256 publicado no Release e cole o conteúdo dele aqui, não a URL do arquivo.', max_length=64, validators=[django.core.validators.RegexValidator(message='Deve ser o hash SHA256 em hexadecimal (64 caracteres) — o conteudo do arquivo .sha256, nao a URL dele.', regex='^[0-9A-Fa-f]{64}$')])),
                ('release_notes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para aposentar uma versão do catálogo (ex.: recall por bug) sem apagar histórico. Uma versão inativa nunca é enviada num push novo, mesmo que ainda esteja na curadoria de algum cliente.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Versão do Agente (SyncAgent/PDV)',
                'verbose_name_plural': 'Catálogo de Versões do Agente',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='integracao_secret',
            field=models.CharField(blank=True, help_text='Gerado no provisionamento. Usado como Bearer token nas chamadas HTTPS do CP para esta instância (ex.: sincronizar versões permitidas). Rotacione se suspeitar de vazamento — reprovisionar/reaplicar módulos gera um novo.', max_length=100, verbose_name='Segredo de integração CP → ERP'),
        ),
        migrations.CreateModel(
            name='SincronizacaoVersoesAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versoes_enviadas', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('enviando', 'Enviando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='enviando', max_length=20)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('resposta_http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sincronizacoes_versoes', to='registry.cliente')),
            ],
            options={
                'verbose_name': 'Sincronização de Versões (CP → ERP)',
                'verbose_name_plural': 'Sincronizações de Versões (CP → ERP)',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='versoes_permitidas',
            field=models.ManyToManyField(blank=True, help_text='Conjunto que este cliente pode escolher para atualizar (curadoria da equipe). O dono da loja escolhe dentro deste conjunto na tela "Atualizar App" do Tray; nunca consegue fazer downgrade, mesmo que uma versão menor esteja marcada aqui (trava do lado erp/SyncAgent). Versões que exigem um ERP mais novo que "Versão ERP" abaixo chegam desabilitadas no Tray, com o motivo.', related_name='clientes', to='registry.versaoagente', verbose_name='Versões do SyncAgent/PDV permitidas'),
        ),
    ]
