# Generated by Django 6.0.5 on 2026-09-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_versao_agente_curadoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='atualizacao_automatica_agente',
            field=models.BooleanField(default=False, help_text='Quando ligado, ignora a curadoria manual abaixo e envia todo o catálogo de versões ATIVAS para o ERP deste cliente. A tela "Atualizar App" do Tray passa a oferecer sempre a versão mais nova compatível — sem a equipe precisar adicionar cada release aqui. As travas de downgrade e de versão mínima de ERP continuam valendo (lado erp/SyncAgent). A lista "Versões permitidas" fica guardada e volta a valer se desligar.', verbose_name='Atualização automática (sempre a última versão)'),
        ),
    ]
