# Generated by Django 6.0.5 on 2026-09-08 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_cliente_atualizacao_automatica_agente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sincronizacaoversoesagente',
            name='iniciada_por',
            field=models.ForeignKey(blank=True, help_text='Quem clicou em "Sincronizar Versões". Vazio = push automático (curadoria/catálogo mudou).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Iniciada por'),
        ),
        migrations.AddField(
            model_name='sincronizacaoversoesagente',
            name='log',
            field=models.TextField(blank=True, default='', help_text='Passo a passo do que foi feito — preenchido linha a linha enquanto roda.', verbose_name='Log da sincronização'),
        ),
    ]
