# Generated by Django 6.0.5 on 2026-09-10 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_sincronizacaoversoesagente_iniciada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='deteccao_versoes_erro',
            field=models.CharField(blank=True, max_length=300, verbose_name='Erro na última coleta de versões'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='versao_erp_detectada',
            field=models.CharField(blank=True, help_text='Lida de GET /health/ (ou /v1/cp/status) da instância. Atualizada pela verificação de saúde e pela coleta de versões.', max_length=20, verbose_name='Versão ERP em execução'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='versoes_detectadas_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Versões verificadas em'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='versao_erp',
            field=models.CharField(blank=True, help_text='Tag da imagem Docker pedida no provisionamento/atualização. Não é necessariamente a versão em execução — veja "Versão Atual".', max_length=20, verbose_name='Versão ERP (alvo)'),
        ),
        migrations.CreateModel(
            name='InstalacaoAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=120)),
                ('installation_label', models.CharField(blank=True, max_length=128, verbose_name='Instalação')),
                ('agent_version', models.CharField(blank=True, max_length=80, verbose_name='Versão do SyncAgent/PDV')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Visto por último')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('connectivity', models.CharField(blank=True, max_length=20, verbose_name='Conectividade')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalacoes_agente', to='registry.cliente')),
            ],
            options={
                'verbose_name': 'Instalação do SyncAgent/PDV',
                'verbose_name_plural': 'Instalações do SyncAgent/PDV',
                'db_table': 'registry_instalacaoagente',
                'ordering': ['installation_label', 'instance_id'],
                'unique_together': {('cliente', 'instance_id')},
            },
        ),
    ]
