# Generated by Django 6.0.5 on 2026-09-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_cliente_deteccao_versoes_erro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tema_site',
            field=models.CharField(choices=[('dedetizadora', 'Dedetizadora (verde)'), ('dedetizadora2', 'Dedetizadora 2 (azul + animações)'), ('loja', 'Loja (claro premium)')], default='loja', help_text='Template visual da landing page pública do cliente.', max_length=50, verbose_name='Tema do site'),
        ),
    ]
